version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: superpower
    ports:
      - "27017:27017"
    volumes:
      - ./.volumes/:/data/db
    networks:
      - mongo-compose-network
networks:
  mongo-compose-network:
    driver: bridge